SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Exam](
	[Id] [nvarchar](128) NOT NULL,
	[TestingAreaId] [nvarchar](128) NOT NULL,
	[DurationInMinutes] [int] NOT NULL,
	[Year] [int] NOT NULL,
	[Term] [tinyint] NOT NULL,
 CONSTRAINT [PK_Exam] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_Exam] UNIQUE NONCLUSTERED 
(
	[TestingAreaId] ASC,
	[Year] ASC,
	[Term] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Exam]  WITH CHECK ADD  CONSTRAINT [FK_Exam_TestingArea] FOREIGN KEY([TestingAreaId])
REFERENCES [dbo].[TestingArea] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Exam] CHECK CONSTRAINT [FK_Exam_TestingArea]
GO
