SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QuestionPicture](
	[Id] [nvarchar](128) NOT NULL,
	[QuestionId] [nvarchar](128) NOT NULL,
	[Image] [image] NOT NULL,
 CONSTRAINT [PK_QuestionPicture] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[QuestionPicture]  WITH CHECK ADD  CONSTRAINT [FK_QuestionPicture_Question] FOREIGN KEY([QuestionId])
REFERENCES [dbo].[Question] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[QuestionPicture] CHECK CONSTRAINT [FK_QuestionPicture_Question]
GO
