SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AnswerStepPicture](
	[Id] [nvarchar](128) NOT NULL,
	[AnswerStepId] [nvarchar](128) NOT NULL,
	[Image] [image] NOT NULL,
 CONSTRAINT [PK_AnswerStepPicture] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[AnswerStepPicture]  WITH CHECK ADD  CONSTRAINT [FK_AnswerStepPicture_AnswerStep] FOREIGN KEY([AnswerStepId])
REFERENCES [dbo].[AnswerStep] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[AnswerStepPicture] CHECK CONSTRAINT [FK_AnswerStepPicture_AnswerStep]
GO
